apps/nowcasting-app/pages/index.tsx
Quick fix before MVP is amde
before
after
ran it locally
=> reformat NG 

apps/nowcasting-app/constant.ts
=> fix: edit api url

apps/nowcasting-app/.eslintignore, apps/nowcasting-app/components/charts/pv-remix-chart.tsx, apps/nowcasting-app/components/charts/remix-line.tsx, apps/nowcasting-app/components/charts/use-format-chart-data.tsx, apps/nowcasting-app/components/footer.tsx, apps/nowcasting-app/components/hooks/use-and-update-selected-time.tsx, apps/nowcasting-app/components/layout.stories.tsx, apps/nowcasting-app/components/layout.tsx, apps/nowcasting-app/components/map/faildState.tsx, apps/nowcasting-app/components/map/index.ts, apps/nowcasting-app/components/map/loadingState.tsx, apps/nowcasting-app/components/map/map.tsx, apps/nowcasting-app/components/map/pvLatest.tsx, apps/nowcasting-app/components/navbar.tsx, apps/nowcasting-app/components/side-layout.tsx, apps/nowcasting-app/components/types.d.ts, apps/nowcasting-app/components/utils.ts, apps/nowcasting-app/package.json, apps/nowcasting-app/pages/404.tsx, apps/nowcasting-app/pages/_app.tsx, apps/nowcasting-app/pages/_document.tsx, apps/nowcasting-app/pages/_error.js, apps/nowcasting-app/pages/api/auth/[...auth0].ts, apps/nowcasting-app/pages/api/forecasts/[...mockApiRoute].ts, apps/nowcasting-app/pages/logout.tsx, apps/nowcasting-app/tsconfig.json, yarn.lock
this pr 
- implements strict typescript rules and updates code types to pass tsc
- also config eslint and prettier and fix lint errors
Closes #49
=> Fix ts eslint

apps/nowcasting-app/components/charts/gsp-pv-remix-chart/index.tsx, apps/nowcasting-app/components/map/pvLatest.tsx
=> click-GSP-tweaks

apps/nowcasting-app/components/map/measuringUnit.tsx, apps/nowcasting-app/components/map/pvLatest.tsx
Remove showing text
Fixes #80 #79
Ran Vercel CI
Ran locally to test behaviour
=> removing 'showing' and default to %

apps/nowcasting-app/components/charts/gsp-pv-remix-chart/use-get-gsp-data.ts, apps/nowcasting-app/components/map/pvLatest.tsx, apps/nowcasting-app/constant.ts
=> load historic/normalized data in the bg

apps/nowcasting-app/pages/index.tsx
=> feat: add feedback link in as a footer of the layout

apps/nowcasting-app/components/charts/gsp-pv-remix-chart/index.tsx, apps/nowcasting-app/components/charts/pv-remix-chart.tsx, apps/nowcasting-app/components/charts/use-format-chart-data.tsx
=> solid line up to now

apps/nowcasting-app/constant.ts
Change MW limit to 400
Fixes #78 
CI tests
=> change to 400MW

apps/nowcasting-app/components/charts/remix-line.tsx
before
after
Fixes #82  
ran it locally
=> switch labels

apps/nowcasting-app/components/charts/gsp-pv-remix-chart/index.tsx, apps/nowcasting-app/components/charts/pv-remix-chart.tsx, apps/nowcasting-app/components/charts/remix-line.tsx, apps/nowcasting-app/constant.ts
add y maximum to national plot
Fixes #103 
ran locally
=> Y max on national

apps/nowcasting-app/components/navbar.tsx, apps/nowcasting-app/package.json
Update the version in package.json and display the full version in the user drop-down menu.
Fixes #
#117 
Visually
=> refactor: change version to 0.2.1

apps/nowcasting-app/components/charts/gsp-pv-remix-chart/index.tsx, apps/nowcasting-app/components/charts/pv-remix-chart.tsx, apps/nowcasting-app/components/charts/remix-line.tsx, apps/nowcasting-app/components/charts/use-format-chart-data.tsx, apps/nowcasting-app/components/map/map.tsx, apps/nowcasting-app/components/map/pvLatest.tsx, apps/nowcasting-app/components/navbar.tsx, apps/nowcasting-app/components/side-layout.tsx, apps/nowcasting-app/constant.ts, apps/nowcasting-app/package.json, apps/nowcasting-app/pages/index.tsx
#71 
What are the changes?
- #83 
- #82 
- #103 
- #78 
- #104 
- #69 
- #101 
- #56 
- #67 
- https://github.com/openclimatefix/nowcasting/issues/120
- fix 4k issue
- https://github.com/openclimatefix/nowcasting/issues/114
- https://github.com/openclimatefix/nowcasting/issues/117
=> Development - first UAT

apps/nowcasting-app/components/charts/remix-line.tsx, apps/nowcasting-app/components/charts/use-format-chart-data.tsx
=> fix/gsp-chart-for-low-pv (#118)

apps/nowcasting-app/components/charts/pv-remix-chart.tsx, apps/nowcasting-app/components/tooltip.tsx, apps/nowcasting-app/package.json, yarn.lock
add tooltip to the chart
Fixes #76
_ tested manually
=> Feat/info text (#76)

apps/nowcasting-app/components/map/pvLatest.tsx, apps/nowcasting-app/constant.ts, apps/nowcasting-app/package.json, apps/nowcasting-app/pages/_app.tsx, apps/nowcasting-app/styles/globals.css, apps/nowcasting-app/styles/toastify.css, yarn.lock
show error alert on request failure 
Fixes #43
- tested locally
=> Feat/error alert #43

apps/nowcasting-app/components/hooks/use-get-time-key-controls.tsx, apps/nowcasting-app/components/hooks/use-hot-key-control-chart.tsx, apps/nowcasting-app/components/map/map.tsx, apps/nowcasting-app/components/play-button/index.tsx, apps/nowcasting-app/components/side-layout.tsx, apps/nowcasting-app/components/utils.ts, apps/nowcasting-app/pages/index.tsx
=> feat/Hot keys (#77)

apps/nowcasting-app/components/charts/forecast-header.tsx, apps/nowcasting-app/components/charts/forecast-header/index.tsx, apps/nowcasting-app/components/charts/forecast-header/ui.tsx, apps/nowcasting-app/components/charts/gsp-pv-remix-chart/index.tsx, apps/nowcasting-app/components/charts/pv-remix-chart.tsx, apps/nowcasting-app/components/charts/use-format-chart-data.tsx, apps/nowcasting-app/components/globalState.tsx, apps/nowcasting-app/components/hooks/use-time-now.tsx, apps/nowcasting-app/components/layout.tsx, apps/nowcasting-app/components/navbar.tsx, apps/nowcasting-app/components/play-button/ui.tsx, apps/nowcasting-app/components/types.d.ts, apps/nowcasting-app/components/utils.ts
=> Feat/national headline stats (#105)

apps/nowcasting-app/components/charts/pv-remix-chart.tsx, apps/nowcasting-app/components/layout.tsx
Fixes #
closes #137 
locally by adding different values to solarStatus object
=> fix: hide status banner condition

apps/nowcasting-app/components/charts/pv-remix-chart.tsx, apps/nowcasting-app/components/hooks/use-hot-key-control-chart.tsx, apps/nowcasting-app/pages/index.tsx
=> fix/ hotkeys range (132)

apps/nowcasting-app/components/charts/forecast-header/ui.tsx
small update to national font
Fixes #
normal UI
=> National font size

apps/nowcasting-app/components/map/pvLatest.tsx
update to v4 map
Fixes #
ran it locally
=> update to new map

apps/nowcasting-app/components/charts/pv-remix-chart.tsx, apps/nowcasting-app/components/hooks/use-hot-key-control-chart.tsx
=> fix hotkeys-range on first load

apps/nowcasting-app/components/charts/forecast-header/ui.tsx, apps/nowcasting-app/components/charts/gsp-pv-remix-chart/forecast-header-gsp.tsx, apps/nowcasting-app/components/footer.tsx, apps/nowcasting-app/components/map/measuringUnit.tsx, apps/nowcasting-app/components/map/pvLatest.tsx, apps/nowcasting-app/components/navbar.tsx, apps/nowcasting-app/components/play-button/ui.tsx, apps/nowcasting-app/components/side-layout.tsx, apps/nowcasting-app/components/utils.ts
Closes #159
Closes #160
Closes #161
Closes #169
=> Small fixes

apps/nowcasting-app/components/map/pvLatest.tsx
testing out map values 
Fixes #174
=> round map values

apps/nowcasting-app/components/side-layout/side-footer/index.tsx
Fixes #197
https://www.loom.com/share/f55fbdb155814179ba73e10578609033
=> copy email on click

apps/nowcasting-app/components/charts/remix-line.tsx
=> change tooltip colors

apps/nowcasting-app/components/charts/pv-remix-chart.tsx, apps/nowcasting-app/components/icons.tsx, apps/nowcasting-app/components/side-layout/index.tsx
Fix #203 as per design (ish)
Fixes #
Manual/visual, simple addition
=> #203: add legend for charts

apps/nowcasting-app/components/map/color-guide-bar.tsx, apps/nowcasting-app/tailwind.config.js
Updated styling and position to match new designs
Fixes #213 
Visually/manually
=> #213: amend key styling

apps/nowcasting-app/components/charts/forecast-header/ui.tsx
Change GW to MW
Fixes #243 
CI and ran locally
=> Change label to MW #242

.all-contributorsrc, README.md, apps/nowcasting-app/components/map/color-guide-bar.tsx, apps/nowcasting-app/constant.ts
Added property in legend item objects to control textColor.
NB. also has `main` changes pulled in to update `development` branch.
Fixes #258 and #244
=> 258 update map key to show 0 50mw with white text

apps/nowcasting-app/components/map/pvLatest.tsx
fix for database, stop it from reloading all the time
- put this on dev, yesterday evening
=> same as commit 'put useEffect back in	1d6225d'

apps/nowcasting-app/pages/api/auth/[...auth0].ts
Fix Auth0 authentication for Preview Deployments on Vercel
Logged in successfully on a Preview Deployment for this branch; can also test yourself here to make sure:
https://nowcasting-m4g57hif8-openclimatefix.vercel.app/
=> Add test auth logic for dev/preview vercel URL

apps/nowcasting-app/components/charts/use-format-chart-data.tsx, apps/nowcasting-app/components/types.d.ts
updates probabilistic forecast code so there isn't an error when api is rolled back to v1.4.8
Ran the code locally.
=> update code to work with api_version 1.4.8

apps/nowcasting-app/components/charts/remix-line.tsx, apps/nowcasting-app/components/charts/use-format-chart-data.tsx, apps/nowcasting-app/components/types.d.ts
Update FE code to work with v1.4.8  - v1.5.4 of the nowcasting API. 
Code was run locally.
=> Fix error running code with Nowcasting API v1.4.8

apps/nowcasting-app/components/charts/remix-line.tsx, apps/nowcasting-app/package.json
Merge changes from staging to main 
Viewed the staging branch
=> v0.4.4 - Probabilistic Charts update for api v1.4.8

apps/nowcasting-app/components/charts/remix-line.tsx, apps/nowcasting-app/package.json
Pull staging into dev to keep `development` up-to-date after minor changes pre-release
Ran the code locally
=> Merge staging to dev

apps/nowcasting-app/components/charts/DataLoadingChartStatus.tsx, apps/nowcasting-app/components/charts/delta-view/delta-view-chart.tsx, apps/nowcasting-app/components/charts/gsp-pv-remix-chart/use-get-gsp-data.ts, apps/nowcasting-app/components/charts/pv-remix-chart.tsx, apps/nowcasting-app/components/charts/remix-line.tsx, apps/nowcasting-app/components/helpers/globalState.tsx, apps/nowcasting-app/components/helpers/utils.ts, apps/nowcasting-app/components/hooks/useLoadDataFromApi.tsx, apps/nowcasting-app/components/icons/icons.tsx, apps/nowcasting-app/components/icons/spinner.tsx, apps/nowcasting-app/components/layout/layout.tsx, apps/nowcasting-app/components/types.d.ts, apps/nowcasting-app/package.json, apps/nowcasting-app/pages/index.tsx, yarn.lock
merge development into branch
- ran locally
- checked vercel - todo
=> merge conflicts from dev

apps/nowcasting-app/components/layout/header/profile-dropdown.tsx, apps/nowcasting-app/pages/logout.tsx
Update email to quartz.support@openclimatefix.org
[Fixes #](https://github.com/openclimatefix/nowcasting/issues/406)
- Updated email in Vercel branch CI
=> update to quartz.support

apps/nowcasting-app/package.json, apps/nowcasting-app/pages/index.tsx
Merging development into staging. 
Fixes #
=> Merge current changes on dev into staging

apps/nowcasting-app/components/charts/solar-site-view/solar-site-tables.tsx
Trivial fix to remove warning in console.
I wasn't sure what you merging procedure was so I made a PR!
=> Fix missing key= in react component

apps/quartz-app/src/components/Sidebar.tsx
The total generation numbers were not adding up correctly. The solar card was not reflecting the right solar generation number. I've changed this and total power should now add up correctly. 
Fixes #483 
Ran the code locally.
=> update solar generation to reflect correct value

apps/quartz-app/app/page.tsx, apps/quartz-app/src/components/Sidebar.tsx, apps/quartz-app/src/components/charts/Tooltip.tsx, apps/quartz-app/src/types/ui.ts
Swap wind and solar in sidebar
Fixes #494 
from
to 
Ran locally
=> Swap solar and wind sidebar

apps/quartz-app/src/components/layout/Header.tsx
Add forecast type and horizon to CSV download file name
Locally and on `development`
=> Add horizon type to csv file name

apps/nowcasting-app/components/charts/ChartLegend.tsx, apps/nowcasting-app/components/charts/gsp-pv-remix-chart/forecast-header-gsp.tsx, apps/nowcasting-app/components/helpers/cookieStorage.ts, apps/nowcasting-app/components/helpers/globalState.tsx, apps/nowcasting-app/components/layout/header/profile-dropdown.tsx, apps/nowcasting-app/components/map/pvLatestMap.tsx, apps/nowcasting-app/pages/index.tsx
Few small things, see commit messages
=> PR comment fixes for Quartz Solar v0.5.2

apps/nowcasting-app/ChartInfo.tsx, apps/nowcasting-app/components/charts/solar-site-view/solar-site-tables.tsx, apps/nowcasting-app/next.config.js, apps/nowcasting-app/package.json, apps/nowcasting-app/pages/api/auth/[...auth0].ts, apps/nowcasting-app/pages/api/forecasts/[...mockApiRoute].ts, apps/quartz-app/.gitignore, apps/quartz-app/app/global-error.tsx, apps/quartz-app/next.config.mjs, apps/quartz-app/package.json, apps/quartz-app/sentry.client.config.ts, apps/quartz-app/sentry.edge.config.ts, apps/quartz-app/sentry.server.config.ts, apps/quartz-app/src/components/Main.tsx, apps/quartz-app/src/components/charts/Tooltip.tsx, apps/quartz-app/src/components/layout/Header.tsx, apps/quartz-app/src/components/layout/LayoutWrapper.tsx, apps/quartz-app/src/hooks/useUserMenu.ts, apps/quartz-app/src/instrumentation.ts, yarn.lock
Add Sentry and configure for general error tracking, and also add log capture on CSV download action. 
Fixes #528 
Locally and on preview branch
=> add Sentry and log when CSV is updated

apps/nowcasting-app/.env.example, apps/nowcasting-app/README.md, apps/nowcasting-app/components/auth/CustomUserProvider.tsx, apps/nowcasting-app/components/charts/remix-line.tsx, apps/nowcasting-app/components/helpers/utils.ts, apps/nowcasting-app/components/layout/header/profile-dropdown.tsx, apps/nowcasting-app/next.config.js, apps/nowcasting-app/package.json, apps/nowcasting-app/pages/_app.tsx, apps/nowcasting-app/pages/api/get_token.ts, apps/nowcasting-app/pages/index.tsx, yarn.lock
Allows Open Source contributors to run the Quartz Solar UI locally without the need for auth0.
Requires the developer to run the also newly updated [Quartz Solar API](https://github.com/openclimatefix/uk-pv-national-gsp-api) locally alongside.
Fixes #505 
=> Non auth dev mode

apps/nowcasting-app/components/charts/gsp-pv-remix-chart/index.tsx, apps/nowcasting-app/components/charts/gsp-pv-remix-chart/use-get-gsp-data.ts, apps/nowcasting-app/components/helpers/data.ts, apps/nowcasting-app/components/map/deltaMap.tsx, apps/nowcasting-app/components/map/pvLatestMap.tsx
- Allow for non-consecutive GSP_IDs
- Small fix for data loading spinner
Fixes #579 
=> GSP Update May 25

apps/nowcasting-app/data/dno_gsp_groupings.json, apps/nowcasting-app/data/dno_license_areas_20200506.json
Rename due to NG buying WPD
Fixes #609
=> rename WPD to NGED in data files
