apps/nowcasting-app/components/charts/pv-remix-chart.tsx, apps/nowcasting-app/components/globalState.tsx, apps/nowcasting-app/components/map/pvLatest.tsx
closes #24 
Get forecast_creation_time from [/v0/GB/solar/gsp/forecast/all](http://nowcasting-api-development.eu-west-1.elasticbeanstalk.com/docs#/default/get_all_available_forecasts_v0_GB_solar_gsp_forecast_all_get) and put it into line chart footer
=> feat: add forecast creation time

apps/nowcasting-app/components/navbar.tsx, apps/nowcasting-app/package.json
closes #32 
Add version to the profile dropdown
Fixes #
Fix hidden text `Signed in as` in the profile dropdown
=> feat: add version to the profile dropdown

apps/nowcasting-app/components/utils.ts
Fix for datestamps on 
target time and forecast creation time
Fixes #24 
Tested it out with
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getUTCDay
=> use d.getUTCDate not d.getUTCDay

apps/nowcasting-app/components/charts/remix-line.tsx, apps/nowcasting-app/components/utils.ts
Change all times to 'Europe/London'
- HH:MM are correct in graph
- forecast creation time is in 'Europe/London'
- target datetime is in 'Europe/London'
This was take around 09:14 Europe London time
Fixes #55 
ran it locally, checked
- forecast creation time
- targte time on graph
- x lables
- label in hover on national gsp
- GSP plot looks correct too
Also CI check it builds
=> make all times Europe London

apps/nowcasting-app/components/charts/pv-remix-chart.tsx
Move forecast creation time up a tiny bit, so that it doesnt over lap the footer
Fixes #
ran locally
=> move forecast creationg time up a bit

apps/nowcasting-app/components/charts/remix-line.tsx
This was definitely my fault, as I've been messing with this
before
after
Fixes #104 
ran locally
=> fix hover time

apps/nowcasting-app/components/map/pvLatest.tsx
Update forecast creation time
Fixes #101 
Ran locally
waited 10 mins, and time did update
=> add set creation time when getting forecast data (#101)

apps/nowcasting-app/components/charts/gsp-pv-remix-chart/index.tsx
Fix ymax on GSP plot to be the installed capacity of the GSP
Need to round up the ymax value to th following levels, so that y major ticks looked right
[3, 9, 20, 45, 60, 100, 200, 300, 450, 600];
Fixes #133 
ran locally
=> Issue/ymax gsp graph (#133)

apps/nowcasting-app/components/charts/gsp-pv-remix-chart/use-get-gsp-data.ts, apps/nowcasting-app/components/charts/pv-remix-chart.tsx, apps/nowcasting-app/constant.ts, apps/nowcasting-app/pages/api/forecasts/[...mockApiRoute].ts
linked with https://github.com/openclimatefix/nowcasting_api/pull/119. This need nowcasting_api>=0.2.13
Change api route from 'truth' to 'pvlive'
Fixes #
=> change truth to pvlive

apps/nowcasting-app/components/map/pvLatest.tsx
Removed `ROUND` button and set default to true. 
NB have left the boolean parameters in place in the round functions as this seems like functionality that make resurface in a different form/use case when the dash becomes more interactive.
Visual testing, and manually switched on and off boolean in code to compare map with rounded/non-rounded figures.
Screenshot attached.
=> #202: remove round button & set default

apps/nowcasting-app/components/charts/pv-remix-chart.tsx
Updates background color or the pv remix chart key to mapbox-black-500. 
Updates font-size to be a little bigger, 12px instead of 11px. It seemed to look better. 
Design suggestion: 
Current: 
New: 
Fixes #215 
Tested visually by running the code locally.
=> update background color of pv remix chart key 

apps/nowcasting-app/components/charts/forecast-header/ui.tsx, apps/nowcasting-app/components/charts/gsp-pv-remix-chart/forecast-header-gsp.tsx, apps/nowcasting-app/components/charts/gsp-pv-remix-chart/index.tsx, apps/nowcasting-app/styles/globals.css, apps/nowcasting-app/styles/toastify.css
Started working on adding gw and mw to the titles using a span to add MW or GW within the div for each title. Would be open to knowing if there are other ways to setting this up. 
It currently looks like this: 
It should look like this: 
Works on #216
Tested visually by running locally.
=> issue 216/add mw gw to titles

apps/nowcasting-app/components/button-group.tsx, apps/nowcasting-app/components/map/measuringUnit.tsx, apps/nowcasting-app/components/utils.ts
Moved buttons and updated the date format. 
There might be an issue with deployment code because I created a variable called `options` when updating the date format in `utils.ts` and typescript in didn't seem to like that. 
The zoom in and out button still needs to be moved. 
Fixes #219 & #220 
Previous: 
Design Suggestion: 
New: 
This was tested visually by running the code locally.
=> Feat/219 move buttons and feat/220 move and update date 

apps/nowcasting-app/.gitignore, apps/nowcasting-app/components/charts/gsp-pv-remix-chart/forecast-header-gsp.tsx, apps/nowcasting-app/components/icons.tsx
imported close icon into forecast-header-gsp and added to button
Updated button with an svg icon and saved in `icons.tsx`. 
I then imported the icon into the `forecast-header-gsp.tsx` file and added the icon to the close button. 
It should look like this in development: 
Fixes #217 
Tested visually by running locally. 
=> feat/217 fixing close button 

apps/nowcasting-app/components/charts/gsp-pv-remix-chart/index.tsx
Add extra GSP maximum heights
added
- 28
- 36
so now all are
const yMax_levels = [3, 9, 20, 28, 36, 45, 60, 80, 100, 120, 160, 200, 240, 300, 320, 360, 400, 450, 600];
Helps with #150 
=> add 28 and 36 for GSP levels

apps/nowcasting-app/components/side-layout/side-footer/index.tsx
Change forecast creation time to `YYYY/MM/DD HH:MM`
Before
Now:
Fixes #242 
run locally
=> change forecast creation time to YYYY/MM/DD HH:MM #242

apps/nowcasting-app/constant.ts
Pretty self explanatory, added in an ENV VAR to set the API prefix for different environments.
**NB env variables should be in Vercel now too, just need double checking in Prod when Development gets merged.**
Fixes #263 
Changed the env var in dev from `api-dev` to `api-pro` and back respectively, seeing the graphs update on restart of dev server.
=> #263: add env var to constant.ts for API_PREFIX

apps/nowcasting-app/components/charts/forecast-header/ui.tsx, apps/nowcasting-app/components/charts/pv-remix-chart.tsx, apps/nowcasting-app/components/map/measuringUnit.tsx, apps/nowcasting-app/components/play-button/ui.tsx, apps/nowcasting-app/components/side-layout/index.tsx
Hotfix for styling bugs:
- Main bug: layout between left and right sections broken - left chart component is adopting full screen height, but is now pushed below the header causing the legend to be below the fold, only visible on scroll, and white gap below map.
- Also included fixes for:
-  National header spacing/padding around forecast figures
- Removed unintended border on measuringUnit button on map (until we show the Capacity option)
=> Fix: legend off-page; national header spacing; unit btn border

apps/nowcasting-app/components/map/deltaMap.tsx, apps/nowcasting-app/components/map/pvLatest.tsx
Remove `slice(1)` function as we are now able to get `/forecast/all` data without the first GSP being National (GSP_0).
Fixes #
=> Remove national gsp slice pv & delta maps

apps/nowcasting-app/components/charts/remix-line.tsx
Font color for plevels in the tooltip are now yellow. 
Fixes #377 
Code was run locally.
=> update plevel font color in tooltip

apps/nowcasting-app/components/charts/remix-line.tsx, apps/nowcasting-app/components/types.d.ts
Added a condition to the `Tooltip code` to not show plevel values when plevel values are < 0. This might not happen often but occasionally a negative number might make its way through the API for mysterious and unknown reasons. 
Fixes #379 
Code was run and viewed locally.
=> return null if plevel values < 0

apps/nowcasting-app/components/charts/gsp-pv-remix-chart/use-get-gsp-data.ts, apps/nowcasting-app/components/layout/layout.tsx, apps/nowcasting-app/constant.ts, apps/nowcasting-app/pages/index.tsx
👋 hi all, Robert Monarch's Coursera course brought me here. I'm hoping I can make myself useful 🙂
Adds a URL param to identify requests coming directly from the web app
Fixes https://github.com/openclimatefix/nowcasting/issues/373 - lmk if I misunderstood the intention here!
I ran the web app and API locally and checked that the param was propagated and persisted to Postgres in some test queries. Example:
```
postgres=# select * from (select distinct on (url, email) * from api_request join "user" on user_uuid = "user".uuid where url like '%national/forecast%' and email not like '%openclimatefix%' order by url, email, created_utc desc) as anon_1 where created_utc > '2023-06-20' order by created_utc desc;
uuid                 |                                               url …
```
=> Add UI tag to routes

apps/nowcasting-app/components/charts/remix-line.tsx, apps/nowcasting-app/components/charts/use-format-chart-data.tsx
Updates the formatting for probabilistic numbers in the tooltip. This was discussed here: #384 . 
The updated tooltip looks like this. 
It might be noticeable that the `OCF Forecast` is now in semi-bold because the `textClass` applied wasn't working, so I fixed that as well when I set the `textClass` for the P levels and values. 
I updated `useFormatChartData` so that it returns 3 probabilistic things: `PROBABILISTIC_RANGE` as an array for the area plotted on the chart and then `PROBABILISTIC_UPPER_BOUND`and `PROBABILISTIC_LOWER_BOUND` as numbers. This seems repetitive, but when it came to the tooltip, it was easy to just have number values for all tooltip labels.
In terms of review, would like to know if all tooltip numbers are still showing correctly. 
Fixes #384
I ran the code locally.
=> Reformat probabilistic numbers in tooltip

apps/nowcasting-app/components/map/sitesMap.tsx
Change the radius of the yellow blob to be
`r = expectedpv ^ 0.66`.
Note orginally it was `r = expectedpv^1`, and I tried `r = expectedpv ^ 0.5`, but something looked a bit wrong. The GSPs that were only at 25% went to half the circle and it looked quite filled out. 
Fixes #437
before
now
=> change circle so that area is proportional to expected PV

.github/workflows/yarn_test.yaml, .husky/pre-commit, apps/nowcasting-app/components/charts/solar-site-view/solar-site-chart.tsx, apps/nowcasting-app/components/charts/solar-site-view/solar-site-tables.tsx, apps/nowcasting-app/components/side-layout/index.tsx, apps/nowcasting-app/package.json
Fix squished Sites View left charts layout; CI flow still not running quite right, but will circle back later
Fixes #541 
Locally and on dev for a month (longer than intended!)
=> Fix Sites View Layout (& CI updates WIP)

apps/nowcasting-app/components/charts/delta-view/delta-view-chart.tsx, apps/nowcasting-app/components/charts/solar-site-view/solar-site-chart.tsx, apps/nowcasting-app/components/side-layout/index.tsx, apps/nowcasting-app/styles/globals.css
Remove extraneous scrollbars and style existing/default best we can.
Fixes #541 extra bug
=> fix ugly scrollbars bug

.gitignore, apps/nowcasting-app/components/charts/pv-remix-chart.tsx, apps/nowcasting-app/components/helpers/chartUtils.test.ts, apps/nowcasting-app/components/helpers/chartUtils.ts, apps/nowcasting-app/components/helpers/utils.test.ts, apps/nowcasting-app/components/helpers/utils.ts, apps/nowcasting-app/constant.ts
Increased the value of MAX_NATIONAL_GENERATION_MW to 18000 (18GW) and to prevent graph from stretching when the max value is exceeded add a buffer of 1000 and round to next 1000th value and set it as yMax  
Fixes #559
Added jest Test cases to new util function
When yMax is 18000 
when yMax is 1000 to indicate data overflow.
=> feat: incresed MAX_NATIONAL_GENERATION_MW and dynamic yMax value

apps/nowcasting-app/components/helpers/data.test.ts, apps/nowcasting-app/components/helpers/data.ts, apps/nowcasting-app/pages/index.tsx
Reimplement the default behaviour of loading all of the GSP forecast history once on page load, by including a start time of the beginning of the default forecast period to the API request to fit the new API behaviour.
> N.B. This will be superseded by the new "cross-sectional" data fetching behaviour to reduce unnecessary data loading
Fixes #563
=> Fix gsp/forecast/all data not loading in past

apps/nowcasting-app/components/charts/delta-view/delta-view-chart.tsx, apps/nowcasting-app/components/charts/gsp-pv-remix-chart/index.tsx, apps/nowcasting-app/components/charts/pv-remix-chart.tsx, apps/nowcasting-app/components/helpers/chartUtils.test.ts, apps/nowcasting-app/components/helpers/chartUtils.ts, apps/nowcasting-app/components/helpers/utils.test.ts, apps/nowcasting-app/components/helpers/utils.ts, apps/nowcasting-app/constant.ts
After discussion with the team, opting to up the National limit to maintain balance between consistency (user being accustomed to a certain scale when glancing at the National chart) and the changeable nature of our forecast daily peaks, probabilistic upper bound, etc.
Also:
- applies the new Y max logic to Delta view (missed by myself when reviewing the recent PR);
- improves the rounding for larger Y max values in the >2000MW range, keeping to 1,000 or 2,500 increments;
- amended the getTicks logic for divisions, in preference order: fifths, sixths, quarters, thirds, sevenths.
Fixes #103 (again)
=> Update UK National capacity chart max constant to 13.5GW

apps/nowcasting-app/components/charts/gsp-pv-remix-chart/index.tsx, apps/nowcasting-app/components/charts/gsp-pv-remix-chart/use-get-gsp-data.ts
Add check for pvlive sort order during PVLive data aggregation
if not new order, reverse the array
Fixes #613
=> add check for pvlive sort order & reverse if needed

apps/nowcasting-app/pages/index.tsx
Reset aggregation to GSP when switching to Delta view.
Fixes #622 
Current dev:
Preview:
=> Reset aggregation to GSP when switching to Delta view
